/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author chumuslavia
 */
public class FrmDeudasPendientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmDeudasPendientes.class.getName());

    /**
     * Creates new form FrmDeudasPendientes
     */
    public FrmDeudasPendientes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new vista.PanelRound();
        panelRound2 = new vista.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        lblPaciente = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDeudas = new javax.swing.JTable();
        lblTotalPendiente = new javax.swing.JLabel();
        lblValorTotalPendiente = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 627));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(153, 153, 153));
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("DEUDAS PENDIENTES");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(380, 380, 380))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        lblPaciente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPaciente.setText("Paciente:");
        panelRound1.add(lblPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 55, -1, -1));
        panelRound1.add(txtPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 55, 663, -1));

        btnBuscar.setBackground(new java.awt.Color(153, 255, 153));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRound1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 55, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 51));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRound1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(866, 55, -1, -1));

        tblDeudas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Paciente", "Servicio", "Total", "Pagado", "Saldo", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblDeudas);
        if (tblDeudas.getColumnModel().getColumnCount() > 0) {
            tblDeudas.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblDeudas.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblDeudas.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblDeudas.getColumnModel().getColumn(3).setPreferredWidth(5);
            tblDeudas.getColumnModel().getColumn(4).setPreferredWidth(5);
            tblDeudas.getColumnModel().getColumn(5).setPreferredWidth(5);
            tblDeudas.getColumnModel().getColumn(6).setPreferredWidth(5);
        }

        panelRound1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 90, 924, -1));

        lblTotalPendiente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalPendiente.setText("Total pendiente:");
        panelRound1.add(lblTotalPendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 535, -1, -1));

        lblValorTotalPendiente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblValorTotalPendiente.setText("0");
        panelRound1.add(lblValorTotalPendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 535, 58, -1));

        btnCerrar.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCerrar.setText("CERRAR ");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);
        panelRound1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 535, -1, -1));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 960, 590));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iberoamericana1107-1000.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FrmReportes().setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmDeudasPendientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblTotalPendiente;
    private javax.swing.JLabel lblValorTotalPendiente;
    private vista.PanelRound panelRound1;
    private vista.PanelRound panelRound2;
    private javax.swing.JTable tblDeudas;
    private javax.swing.JTextField txtPaciente;
    // End of variables declaration//GEN-END:variables
}
