/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import dao.PacienteDAO;
import modelo.Paciente;
import javax.swing.JOptionPane;

/**
 *
 * @author chumuslavia
 */
public class FrmModificarPaciente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmModificarPaciente.class.getName());

    /**
     * Creates new form FrmModificarPaciente
     */
    public FrmModificarPaciente(int idPaciente) {
        initComponents();
        setLocationRelativeTo(null);
        cargarPaciente(idPaciente);
    }
    
    private void cargarPaciente(int idPaciente) {

    PacienteDAO dao = new PacienteDAO();

    Paciente p = dao.buscarPorId(idPaciente);

    if (p == null) {

        JOptionPane.showMessageDialog(
                this,
                "No se encontró el paciente.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    lblId.setText(String.valueOf(p.getIdPaciente()));
    txtDni.setText(p.getDni());
    txtNombres.setText(p.getNombres());
    txtApellidos.setText(p.getApellidos());
    txtFechaNacimiento.setText(p.getFechaNacimiento().toString());
    cmbSexo.setSelectedItem(p.getSexo());
    txtTelefono.setText(p.getTelefono());
    txtDireccion.setText(p.getDireccion());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new vista.PanelRound();
        panelRound2 = new vista.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        lblIdPaciente = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblFechaNacimiento = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        lblDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        btnGuardarCambios = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 627));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 627));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(153, 153, 153));
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("MODIFICAR PACIENTE");
        panelRound2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 6, -1, -1));

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        lblIdPaciente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIdPaciente.setText("ID del paciente:");
        panelRound1.add(lblIdPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 56, -1, -1));

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        panelRound1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 56, 97, 20));

        lblNombres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombres.setText("Nombres:");
        panelRound1.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 160, 67, -1));
        panelRound1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 192, 555, -1));

        lblApellidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblApellidos.setText("Apellidos:");
        panelRound1.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 232, -1, -1));
        panelRound1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 264, 555, -1));

        lblFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaNacimiento.setText("Fecha de nacimiento:");
        panelRound1.add(lblFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 304, -1, -1));
        panelRound1.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 336, 144, -1));

        lblDni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDni.setText("DNI:");
        panelRound1.add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 37, -1));
        panelRound1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 120, 555, -1));

        lblSexo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSexo.setText("Sexo: ");
        panelRound1.add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 376, -1, -1));

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otro" }));
        panelRound1.add(cmbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 376, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTelefono.setText("Teléfono:");
        panelRound1.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 416, -1, -1));
        panelRound1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 448, 555, -1));

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDireccion.setText("Dirección:");
        panelRound1.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        txtDireccion.addActionListener(this::txtDireccionActionPerformed);
        panelRound1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 555, -1));

        btnGuardarCambios.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardarCambios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarCambios.setText("GUARDAR CAMBIOS");
        btnGuardarCambios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarCambios.addActionListener(this::btnGuardarCambiosActionPerformed);
        panelRound1.add(btnGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        panelRound1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, -1, -1));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 620, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iberoamericana1107-1000.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        // TODO add your handling code here:
        
          try {
        Paciente paciente = new Paciente();

        // ID solamente para identificar al paciente.
        // No se modifica.
        paciente.setIdPaciente(Integer.parseInt(lblId.getText()));

        // Datos editables
        paciente.setDni(txtDni.getText().trim());
        paciente.setNombres(txtNombres.getText().trim());
        paciente.setApellidos(txtApellidos.getText().trim());

        paciente.setFechaNacimiento(
                java.sql.Date.valueOf(txtFechaNacimiento.getText().trim())
        );

        paciente.setSexo(cmbSexo.getSelectedItem().toString());
        paciente.setTelefono(txtTelefono.getText().trim());
        paciente.setDireccion(txtDireccion.getText().trim());

        PacienteDAO dao = new PacienteDAO();

        if (dao.modificar(paciente)) {

            JOptionPane.showMessageDialog(
                    this,
                    "Paciente modificado correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
            );

            // Cerrar ventana de modificación
            this.dispose();

            // Volver a FrmPacientes
            FrmPacientes ventanaPacientes = new FrmPacientes();
            ventanaPacientes.setVisible(true);

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo modificar el paciente.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    } catch (IllegalArgumentException e) {

        JOptionPane.showMessageDialog(
                this,
                "La fecha debe tener el formato AAAA-MM-DD.",
                "Fecha incorrecta",
                JOptionPane.WARNING_MESSAGE
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error al modificar el paciente: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        
        this.dispose();

    FrmPacientes ventanaPacientes = new FrmPacientes();
    ventanaPacientes.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmModificarPaciente(1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdPaciente;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefono;
    private vista.PanelRound panelRound1;
    private vista.PanelRound panelRound2;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
