/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.Sesion;
import modelo.Usuario;
import javax.swing.JOptionPane;
//que haces viendo el codigo?

/**
 *
 * @author chumuslavia
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName());

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        cargarDatosUsuario();
        configurarPermisos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new vista.PanelRound();
        panelRound2 = new vista.PanelRound();
        panelRound3 = new vista.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        panelRound4 = new vista.PanelRound();
        lblTextoRol = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        panelRound5 = new vista.PanelRound();
        lblTextoUsuario = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnAnalisis = new javax.swing.JButton();
        btnHistoriaClinica = new javax.swing.JButton();
        btnPacientes = new javax.swing.JButton();
        btnCostos = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(153, 153, 153));
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound3.setBackground(new java.awt.Color(0, 204, 204));
        panelRound3.setRoundBottomLeft(50);
        panelRound3.setRoundBottomRight(50);
        panelRound3.setRoundTopLeft(50);
        panelRound3.setRoundTopRight(50);

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        jLabel2.setText("CLÍNICA IBEROAMERICANA");

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelRound2.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 70));

        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundBottomRight(20);
        panelRound4.setRoundTopLeft(20);
        panelRound4.setRoundTopRight(20);

        lblTextoRol.setText("ROL :");

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextoRol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRol, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound4Layout.createSequentialGroup()
                        .addComponent(lblTextoRol)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(lblRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelRound2.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 170, 30));

        panelRound5.setRoundBottomLeft(20);
        panelRound5.setRoundBottomRight(20);
        panelRound5.setRoundTopLeft(20);
        panelRound5.setRoundTopRight(20);

        lblTextoUsuario.setText("USUARIO :");

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound5Layout.createSequentialGroup()
                        .addComponent(lblTextoUsuario)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelRound2.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 170, 30));

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 90));

        btnCerrarSesion.setBackground(new java.awt.Color(255, 51, 51));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCerrarSesion.setText("CERRAR SESIÓN");
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);
        panelRound1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 175, 78));

        btnAnalisis.setBackground(new java.awt.Color(153, 255, 153));
        btnAnalisis.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        btnAnalisis.setText("ANÁLISIS");
        btnAnalisis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnalisis.addActionListener(this::btnAnalisisActionPerformed);
        panelRound1.add(btnAnalisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 175, 78));

        btnHistoriaClinica.setBackground(new java.awt.Color(153, 255, 153));
        btnHistoriaClinica.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btnHistoriaClinica.setText("HISTORIA CLÍNICA");
        btnHistoriaClinica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistoriaClinica.addActionListener(this::btnHistoriaClinicaActionPerformed);
        panelRound1.add(btnHistoriaClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 175, 80));

        btnPacientes.setBackground(new java.awt.Color(153, 255, 153));
        btnPacientes.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        btnPacientes.setText("PACIENTES");
        btnPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPacientes.addActionListener(this::btnPacientesActionPerformed);
        panelRound1.add(btnPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 175, 78));

        btnCostos.setBackground(new java.awt.Color(153, 255, 153));
        btnCostos.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 36)); // NOI18N
        btnCostos.setText("COSTOS");
        btnCostos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCostos.addActionListener(this::btnCostosActionPerformed);
        panelRound1.add(btnCostos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 175, 78));

        btnReportes.setBackground(new java.awt.Color(153, 255, 153));
        btnReportes.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        btnReportes.setText("REPORTES");
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.addActionListener(this::btnReportesActionPerformed);
        panelRound1.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 175, 78));

        btnUsuarios.setBackground(new java.awt.Color(153, 255, 153));
        btnUsuarios.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        btnUsuarios.setText("USUARIOS");
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.addActionListener(this::btnUsuariosActionPerformed);
        panelRound1.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 175, 78));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/yopng.png"))); // NOI18N
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 540, -1, -1));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 950, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iberoamericana1107-1000.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 998, 629));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void cargarDatosUsuario() {

    if (!Sesion.haySesion()) {

        JOptionPane.showMessageDialog(
                this,
                "No existe una sesión activa.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

        dispose();
        return;
    }

    Usuario usuario = Sesion.getUsuarioActual();

    lblUsuario.setText(usuario.getNombre());
    lblRol.setText(usuario.getRol());
}

private void configurarPermisos() {

    boolean esOwner = Sesion.esOwner();
    boolean esAdministrador = Sesion.esAdministrador();

    // Ocultar por defecto
    btnUsuarios.setVisible(false);

    // Owner y Administrador pueden acceder
    if (esOwner || esAdministrador) {
        btnUsuarios.setVisible(true);
    }
}

private void cerrarSesion() {

    int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de cerrar la sesión?",
            "Cerrar sesión",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
    );

    if (opcion == JOptionPane.YES_OPTION) {

        Sesion.cerrarSesion();

        login ventanaLogin = new login();
        ventanaLogin.setLocationRelativeTo(null);
        ventanaLogin.setVisible(true);

        this.dispose();
    }
}
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        cerrarSesion();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesActionPerformed
        // TODO add your handling code here:
        FrmPacientes ventanaPacientes = new FrmPacientes();
        ventanaPacientes.setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_btnPacientesActionPerformed

    private void btnHistoriaClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaClinicaActionPerformed
        // TODO add your handling code here:
        FrmBuscarPaciente buscar = new FrmBuscarPaciente("HISTORIA");
buscar.setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnHistoriaClinicaActionPerformed

    private void btnAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisisActionPerformed
        // TODO add your handling code here:
        FrmBuscarPaciente buscar = new FrmBuscarPaciente("ANALISIS");
    buscar.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnAnalisisActionPerformed

    private void btnCostosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCostosActionPerformed
        // TODO add your handling code here:
        FrmBuscarPaciente buscar = new FrmBuscarPaciente("COSTOS");
    buscar.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnCostosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        FrmUsuarios ventanaUsuarios = new FrmUsuarios();
        ventanaUsuarios.setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        FrmReportes ventanaReportes = new FrmReportes();
        ventanaReportes.setVisible(true);
    
    this.dispose();
        
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalisis;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCostos;
    private javax.swing.JButton btnHistoriaClinica;
    private javax.swing.JButton btnPacientes;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTextoRol;
    private javax.swing.JLabel lblTextoUsuario;
    private javax.swing.JLabel lblUsuario;
    private vista.PanelRound panelRound1;
    private vista.PanelRound panelRound2;
    private vista.PanelRound panelRound3;
    private vista.PanelRound panelRound4;
    private vista.PanelRound panelRound5;
    // End of variables declaration//GEN-END:variables
}
