/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import dao.UsuarioDAO;
import modelo.Usuario;
import javax.swing.JOptionPane;
import controlador.Sesion;

/**
 *
 * @author chumuslavia
 */
public class FrmNuevoUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmNuevoUsuario.class.getName());
    private FrmUsuarios ventanaUsuarios;
    private UsuarioDAO usuarioDAO;
    

    /**
     * Creates new form FrmNuevoUsuario
     */
    public FrmNuevoUsuario(FrmUsuarios ventanaUsuarios) {
    initComponents();
    setLocationRelativeTo(null);

    this.ventanaUsuarios = ventanaUsuarios;
    this.usuarioDAO = new UsuarioDAO();

    configurarRoles();
    }
    
    private void configurarRoles() {

    Usuario usuarioActual = Sesion.getUsuarioActual();

    if (usuarioActual == null) {

        JOptionPane.showMessageDialog(
                this,
                "No hay una sesión activa.",
                "Acceso denegado",
                JOptionPane.ERROR_MESSAGE
        );

        btnGuardar.setEnabled(false);
        cmbRol.setEnabled(false);

        return;
    }

    String rolActual = usuarioActual.getRol();

    // Limpiar los roles actuales
    cmbRol.removeAllItems();

    // =====================================================
    // OWNER
    // Puede crear Administradores y demás usuarios
    // NO puede crear otro Owner
    // =====================================================

    if ("Owner".equalsIgnoreCase(rolActual)) {

        cmbRol.addItem("Administrador");
        cmbRol.addItem("Recepción");
        cmbRol.addItem("Médico");
        cmbRol.addItem("Laboratorio");

        return;
    }

    // =====================================================
    // ADMINISTRADOR
    // NO puede crear Administradores
    // Solo usuarios normales
    // =====================================================

    if ("Administrador".equalsIgnoreCase(rolActual)) {

        cmbRol.addItem("Recepción");
        cmbRol.addItem("Médico");
        cmbRol.addItem("Laboratorio");

        return;
    }

    // =====================================================
    // RECEPCIÓN / MÉDICO / LABORATORIO
    // No pueden crear usuarios
    // =====================================================

    cmbRol.setEnabled(false);
    btnGuardar.setEnabled(false);

    JOptionPane.showMessageDialog(
            this,
            "Su rol no tiene permisos para crear usuarios.",
            "Acceso denegado",
            JOptionPane.WARNING_MESSAGE
    );
}

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new vista.PanelRound();
        panelRound2 = new vista.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtConfirmarContrasena = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 627));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(153, 153, 153));
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("NUEVO USUARIO");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Usuario:");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 55, -1, -1));
        panelRound1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 55, 471, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 110, -1, -1));
        panelRound1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 110, 468, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Contraseña:");
        panelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 169, -1, -1));

        txtContrasena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelRound1.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 166, 446, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Confirmar contraseña:");
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 234, -1, -1));

        txtConfirmarContrasena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelRound1.add(txtConfirmarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 231, 376, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Rol:");
        panelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 288, 37, -1));

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Recepción", "Médico", "Laboratorio" }));
        panelRound1.add(cmbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 288, 149, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Estado:");
        panelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 348, -1, -1));

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        panelRound1.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 348, 136, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/yo100x100png.png"))); // NOI18N
        panelRound1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 484, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        panelRound1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 462, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        panelRound1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 462, -1, -1));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 640, 590));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iberoamericana1107-1000.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        ventanaUsuarios.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // =====================================================
    // 1. VERIFICAR SESIÓN
    // =====================================================

    Usuario usuarioActual = Sesion.getUsuarioActual();

    if (usuarioActual == null) {

        JOptionPane.showMessageDialog(
                this,
                "No hay una sesión activa.",
                "Acceso denegado",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    String rolActual = usuarioActual.getRol();


    // =====================================================
    // 2. OBTENER EL ROL QUE SE QUIERE CREAR
    // =====================================================

    if (cmbRol.getSelectedItem() == null) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccione un rol.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    String rolNuevo = cmbRol.getSelectedItem().toString();


    // =====================================================
    // 3. NUNCA SE PUEDE CREAR UN OWNER
    // =====================================================

    if ("Owner".equalsIgnoreCase(rolNuevo)) {

        JOptionPane.showMessageDialog(
                this,
                "No se puede crear un Owner desde este sistema.",
                "Acceso denegado",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }


    // =====================================================
    // 4. SOLO OWNER PUEDE CREAR ADMINISTRADORES
    // =====================================================

    if ("Administrador".equalsIgnoreCase(rolNuevo)
            && !"Owner".equalsIgnoreCase(rolActual)) {

        JOptionPane.showMessageDialog(
                this,
                "Solo el Owner puede crear usuarios Administrador.",
                "Acceso denegado",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }


    // =====================================================
    // 5. SOLO OWNER Y ADMINISTRADOR PUEDEN CREAR USUARIOS
    // =====================================================

    if (!"Owner".equalsIgnoreCase(rolActual)
            && !"Administrador".equalsIgnoreCase(rolActual)) {

        JOptionPane.showMessageDialog(
                this,
                "Su rol no tiene permisos para crear usuarios.",
                "Acceso denegado",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }


    // =====================================================
    // 6. OBTENER DATOS DEL FORMULARIO
    // =====================================================

    String usuario = txtUsuario.getText().trim();
    String nombre = txtNombre.getText().trim();
    String password = new String(txtContrasena.getPassword());
    String confirmarPassword =
            new String(txtConfirmarContrasena.getPassword());

    String estado = cmbEstado.getSelectedItem().toString();


    // =====================================================
    // 7. VALIDAR CAMPOS
    // =====================================================

    if (usuario.isEmpty()
            || nombre.isEmpty()
            || password.isEmpty()
            || confirmarPassword.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Complete todos los campos.",
                "Campos incompletos",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }


    // =====================================================
    // 8. CONFIRMAR CONTRASEÑA
    // =====================================================

    if (!password.equals(confirmarPassword)) {

        JOptionPane.showMessageDialog(
                this,
                "Las contraseñas no coinciden.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }


    // =====================================================
    // 9. CREAR OBJETO USUARIO
    // =====================================================

    Usuario nuevoUsuario = new Usuario();

    nuevoUsuario.setUsuario(usuario);
    nuevoUsuario.setNombre(nombre);
    nuevoUsuario.setPassword(password);
    nuevoUsuario.setRol(rolNuevo);
    nuevoUsuario.setEstado(estado);


    // =====================================================
    // 10. REGISTRAR EN BASE DE DATOS
    // =====================================================

    if (usuarioDAO.registrar(nuevoUsuario)) {

        JOptionPane.showMessageDialog(
                this,
                "Usuario registrado correctamente.",
                "Registro exitoso",
                JOptionPane.INFORMATION_MESSAGE
        );

        ventanaUsuarios.actualizarUsuarios();
        ventanaUsuarios.setVisible(true);

        this.dispose();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "No se pudo registrar el usuario.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(() -> {
    FrmUsuarios ventana = new FrmUsuarios();
    ventana.setVisible(true);
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private vista.PanelRound panelRound1;
    private vista.PanelRound panelRound2;
    private javax.swing.JPasswordField txtConfirmarContrasena;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
