/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author chumuslavia
 */
public class FrmNuevaConsulta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmNuevaConsulta.class.getName());
    

    /**
     * Creates new form FrmNuevaConsulta
     */
    public FrmNuevaConsulta() {
        initComponents();
        setLocationRelativeTo(null);

    cargarFecha();
    }
    private modelo.Paciente paciente;
    private modelo.Usuario usuario;

public FrmNuevaConsulta(modelo.Paciente paciente, modelo.Usuario usuario) {

    initComponents();
    setLocationRelativeTo(null);

    this.paciente = paciente;
    this.usuario = usuario;

    cargarPaciente();
    cargarFecha();
}
private void cargarPaciente() {

    if (paciente == null) {
        return;
    }

    lblPaciente.setText(
        paciente.getNombres() + " " +
        paciente.getApellidos()
    );

    lblDni.setText(
        paciente.getDni()
    );
}
private void cargarFecha() {

    SimpleDateFormat formato =
            new SimpleDateFormat("dd/MM/yyyy");

    txtFecha.setText(
            formato.format(new Date())
    );
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new vista.PanelRound();
        panelRound2 = new vista.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPaciente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbMedico = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDiagnostico = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTratamiento = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 627));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(153, 153, 153));
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("NUEVA CONSULTA");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Paciente:");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lblPaciente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPaciente.setText("jLabel3");
        panelRound1.add(lblPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 60, 383, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("DNI:");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 92, 37, -1));

        lblDni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDni.setText("jLabel5");
        panelRound1.add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 92, 133, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Médico:");
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        cmbMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar médico" }));
        panelRound1.add(cmbMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 278, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Fecha de consulta:");
        panelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txtFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFecha.setText("27/08/2026");
        panelRound1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 196, 126, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Diagnóstico:");
        panelRound1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 234, -1, -1));
        panelRound1.add(txtDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 562, 62));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Tratamiento:");
        panelRound1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 334, -1, -1));

        txtObservaciones.addActionListener(this::txtObservacionesActionPerformed);
        panelRound1.add(txtObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 562, 62));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Observaciones:");
        panelRound1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 434, -1, -1));
        panelRound1.add(txtTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 562, 62));

        btnGuardar.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        panelRound1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRound1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 560, -1, -1));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 630, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iberoamericana1107-1000.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObservacionesActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (paciente == null) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se ha seleccionado ningún paciente."
        );
        return;
    }

    String diagnostico = txtDiagnostico.getText().trim();
    String tratamiento = txtTratamiento.getText().trim();
    String observaciones = txtObservaciones.getText().trim();

    if (diagnostico.isEmpty() || tratamiento.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Complete el diagnóstico y tratamiento."
        );
        return;
    }

    modelo.Consulta consulta = new modelo.Consulta();

    consulta.setIdPaciente(paciente.getIdPaciente());
consulta.setIdUsuario(usuario.getIdUsuario());
consulta.setDiagnostico(diagnostico);
    consulta.setTratamiento(tratamiento);
    consulta.setObservaciones(observaciones);

    dao.ConsultaDAO consultaDAO = new dao.ConsultaDAO();

    if (consultaDAO.registrar(consulta)) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Consulta registrada correctamente."
        );

        dispose();

    } else {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error al registrar la consulta."
        );
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmNuevaConsulta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblPaciente;
    private vista.PanelRound panelRound1;
    private vista.PanelRound panelRound2;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtTratamiento;
    // End of variables declaration//GEN-END:variables
}
