/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author chumuslavia
 */
public class Frmnose extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frmnose.class.getName());

    /**
     * Creates new form Frmnose
     */
    public Frmnose() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new vista.PanelRound();
        panelRound2 = new vista.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablepacientes = new javax.swing.JTable();
        btonHistoriaclinica = new javax.swing.JButton();
        btonAnalisis = new javax.swing.JButton();
        btonCostos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 627));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(153, 153, 153));
        panelRound2.setRoundTopLeft(30);
        panelRound2.setRoundTopRight(30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("BUSQUEDA?");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(jLabel3)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("PACIENTE:");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 58, -1, -1));

        txtBuscar.setText("jTextField1");
        panelRound1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 58, 741, -1));

        btonBuscar.setBackground(new java.awt.Color(153, 255, 153));
        btonBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btonBuscar.setText("BUSCAR");
        btonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRound1.add(btonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(856, 58, -1, -1));

        tablepacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI", "NOMBRE", "APELLIDO", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(tablepacientes);
        if (tablepacientes.getColumnModel().getColumnCount() > 0) {
            tablepacientes.getColumnModel().getColumn(0).setPreferredWidth(1);
            tablepacientes.getColumnModel().getColumn(1).setPreferredWidth(5);
            tablepacientes.getColumnModel().getColumn(2).setPreferredWidth(200);
            tablepacientes.getColumnModel().getColumn(3).setPreferredWidth(200);
            tablepacientes.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        panelRound1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 87, 911, 469));

        btonHistoriaclinica.setBackground(new java.awt.Color(153, 255, 153));
        btonHistoriaclinica.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btonHistoriaclinica.setText("HISTORIA CLINICA");
        btonHistoriaclinica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRound1.add(btonHistoriaclinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 562, -1, -1));

        btonAnalisis.setBackground(new java.awt.Color(153, 255, 153));
        btonAnalisis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btonAnalisis.setText("ANALISIS");
        btonAnalisis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRound1.add(btonAnalisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 562, -1, -1));

        btonCostos.setBackground(new java.awt.Color(153, 255, 153));
        btonCostos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btonCostos.setText("COSTOS");
        btonCostos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRound1.add(btonCostos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 562, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("VOLVER");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(this::jButton3ActionPerformed);
        panelRound1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 562, -1, -1));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 950, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iberoamericana1107-1000.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
menu.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Frmnose().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btonAnalisis;
    private javax.swing.JButton btonBuscar;
    private javax.swing.JButton btonCostos;
    private javax.swing.JButton btonHistoriaclinica;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private vista.PanelRound panelRound1;
    private vista.PanelRound panelRound2;
    private javax.swing.JTable tablepacientes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
