/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import dao.PacienteDAO;
import modelo.Paciente;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
//alguien lee estas cosas?

/**
 *
 * @author chumuslavia
 */
public class FrmPacientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPacientes.class.getName());

    /**
     * Creates new form FrmPacientes
     */
    public FrmPacientes() {
        initComponents();
        setLocationRelativeTo(null);
        cargarPacientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new vista.PanelRound();
        panelRound2 = new vista.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(153, 153, 153));
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("GESTIÓN DE PACIENTES");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel2)
                .addContainerGap(356, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Buscar paciente:");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        panelRound1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 660, 30));

        btnBuscar.setBackground(new java.awt.Color(153, 255, 153));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);
        panelRound1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, 90, 30));

        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI", "Nombres", "Apellidos", "Teléfono", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblPacientes);
        if (tblPacientes.getColumnModel().getColumnCount() > 0) {
            tblPacientes.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblPacientes.getColumnModel().getColumn(1).setPreferredWidth(10);
            tblPacientes.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblPacientes.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblPacientes.getColumnModel().getColumn(4).setPreferredWidth(15);
            tblPacientes.getColumnModel().getColumn(5).setPreferredWidth(150);
        }

        panelRound1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 940, 390));

        btnNuevo.setBackground(new java.awt.Color(153, 255, 153));
        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);
        panelRound1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        btnModificar.setBackground(new java.awt.Color(153, 255, 153));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        panelRound1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        panelRound1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, -1, -1));

        btnVolver.setBackground(new java.awt.Color(255, 51, 51));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolver.setText("VOLVER");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(this::btnVolverActionPerformed);
        panelRound1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, -1, -1));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iberoamericana1107-1000.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String texto = txtBuscar.getText().trim();

    PacienteDAO dao = new PacienteDAO();

    List<Paciente> lista;

    if (texto.isEmpty()) {
        lista = dao.listar();
    } else {
        lista = dao.buscar(texto);
    }

    DefaultTableModel modelo = (DefaultTableModel) tblPacientes.getModel();

    modelo.setRowCount(0);

    for (Paciente p : lista) {

        modelo.addRow(new Object[]{
            p.getIdPaciente(),
            p.getDni(),
            p.getNombres(),
            p.getApellidos(),
            p.getTelefono(),
            "ACTIVO"
        });
    }

    if (lista.isEmpty() && !texto.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "No se encontraron pacientes.",
                "Búsqueda",
                JOptionPane.INFORMATION_MESSAGE
        );
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    
    
    
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
menu.setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = tblPacientes.getSelectedRow();

    if (fila == -1) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccione un paciente de la tabla.",
                "Paciente no seleccionado",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    int idPaciente = (int) tblPacientes.getValueAt(fila, 0);

    String nombre = tblPacientes.getValueAt(fila, 2).toString();
    String apellido = tblPacientes.getValueAt(fila, 3).toString();

    int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de eliminar al paciente?\n\n"
            + nombre + " " + apellido,
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (opcion == JOptionPane.YES_OPTION) {

        PacienteDAO dao = new PacienteDAO();

        if (dao.eliminar(idPaciente)) {

            JOptionPane.showMessageDialog(
                    this,
                    "Paciente eliminado correctamente.",
                    "Eliminación exitosa",
                    JOptionPane.INFORMATION_MESSAGE
            );

            cargarPacientes();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo eliminar el paciente.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        FrmRegistrarPaciente ventana = new FrmRegistrarPaciente();
    ventana.setLocationRelativeTo(null);
    ventana.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        
        int fila = tblPacientes.getSelectedRow();

    if (fila == -1) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccione un paciente de la tabla.",
                "Paciente no seleccionado",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    int idPaciente = (int) tblPacientes.getValueAt(fila, 0);

    FrmModificarPaciente ventana = new FrmModificarPaciente(idPaciente);

    ventana.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnModificarActionPerformed
private void cargarPacientes() {

    PacienteDAO dao = new PacienteDAO();

    List<Paciente> lista = dao.listar();

    DefaultTableModel modelo = (DefaultTableModel) tblPacientes.getModel();

    modelo.setRowCount(0);

    for (Paciente p : lista) {

        modelo.addRow(new Object[]{
            p.getIdPaciente(),
            p.getDni(),
            p.getNombres(),
            p.getApellidos(),
            p.getTelefono(),
            "ACTIVO"
        });
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPacientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private vista.PanelRound panelRound1;
    private vista.PanelRound panelRound2;
    private javax.swing.JTable tblPacientes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
