/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author chumuslavia
 */
public class FrmReportes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmReportes.class.getName());

    /**
     * Creates new form FrmReportes
     */
    public FrmReportes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new vista.PanelRound();
        panelRound2 = new vista.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        btnHistorialPagos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnReportePacientes = new javax.swing.JButton();
        btnIngresos = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnDeudasPendientes = new javax.swing.JButton();
        btnCostosServicio1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 627));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(153, 153, 153));
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("REPORTES");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(434, 434, 434)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        btnHistorialPagos.setBackground(new java.awt.Color(153, 255, 153));
        btnHistorialPagos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHistorialPagos.setText("HISTORIAL DE PAGOS");
        btnHistorialPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorialPagos.addActionListener(this::btnHistorialPagosActionPerformed);
        panelRound1.add(btnHistorialPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 132, 220, 81));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/yopng.png"))); // NOI18N
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 544, -1, -1));

        btnReportePacientes.setBackground(new java.awt.Color(153, 255, 153));
        btnReportePacientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReportePacientes.setText("REPORTE DE PACIENTES");
        btnReportePacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportePacientes.addActionListener(this::btnReportePacientesActionPerformed);
        panelRound1.add(btnReportePacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 240, 81));

        btnIngresos.setBackground(new java.awt.Color(153, 255, 153));
        btnIngresos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIngresos.setText("INGRESOS");
        btnIngresos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresos.addActionListener(this::btnIngresosActionPerformed);
        panelRound1.add(btnIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 302, 193, 81));

        btnCerrar.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCerrar.setText("CERRAR");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);
        panelRound1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 453, 193, 81));

        btnDeudasPendientes.setBackground(new java.awt.Color(153, 255, 153));
        btnDeudasPendientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDeudasPendientes.setText("DEUDAS PENDIENTES");
        btnDeudasPendientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeudasPendientes.addActionListener(this::btnDeudasPendientesActionPerformed);
        panelRound1.add(btnDeudasPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 132, 220, 81));

        btnCostosServicio1.setBackground(new java.awt.Color(153, 255, 153));
        btnCostosServicio1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCostosServicio1.setText("COSTOS POR SERVICIO");
        btnCostosServicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCostosServicio1.addActionListener(this::btnCostosServicio1ActionPerformed);
        panelRound1.add(btnCostosServicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 230, 81));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 960, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iberoamericana1107-1000.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FrmMenuPrincipal().setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnHistorialPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialPagosActionPerformed
        // TODO add your handling code here:
        FrmHistorialPagos ventanaHistorialPagos = new FrmHistorialPagos();
        ventanaHistorialPagos.setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_btnHistorialPagosActionPerformed

    private void btnDeudasPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeudasPendientesActionPerformed
        // TODO add your handling code here:
        FrmDeudasPendientes ventanaDeudasPendeientes = new FrmDeudasPendientes();
        ventanaDeudasPendeientes.setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_btnDeudasPendientesActionPerformed

    private void btnCostosServicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCostosServicio1ActionPerformed
        // TODO add your handling code here:
        FrmCostosServicio ventanaCostosServicio = new FrmCostosServicio();
        ventanaCostosServicio.setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_btnCostosServicio1ActionPerformed

    private void btnIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosActionPerformed
        // TODO add your handling code here:
        FrmReporteIngresos ventanaReporteIngresos = new FrmReporteIngresos();
        ventanaReporteIngresos.setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_btnIngresosActionPerformed

    private void btnReportePacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportePacientesActionPerformed
        // TODO add your handling code here:
        FrmReportePacientes ventanaReportePacientes = new FrmReportePacientes();
        ventanaReportePacientes.setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_btnReportePacientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmReportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCostosServicio1;
    private javax.swing.JButton btnDeudasPendientes;
    private javax.swing.JButton btnHistorialPagos;
    private javax.swing.JButton btnIngresos;
    private javax.swing.JButton btnReportePacientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private vista.PanelRound panelRound1;
    private vista.PanelRound panelRound2;
    // End of variables declaration//GEN-END:variables
}
