/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author chumuslavia
 */
public class FrmRegistrarPago extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmRegistrarPago.class.getName());

    /**
     * Creates new form FrmRegistrarPago
     */
    public FrmRegistrarPago() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new vista.PanelRound();
        panelRound2 = new vista.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPaciente = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblValorServicio = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblValorTotalDeuda = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblValorTotalPagado = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblValorSaldoPendiente = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNuevoPago = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmbMetodoPago = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lblValorFechaPago = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblValorEstado = new javax.swing.JLabel();
        btnRegistrarPago = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 627));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(153, 153, 153));
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("REGISTRAR PAGO");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Paciente:");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 55, -1, -1));

        lblPaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPaciente.setText("jLabel4");
        panelRound1.add(lblPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 55, 477, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Servicio:");
        panelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 93, 62, -1));

        lblValorServicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblValorServicio.setText("jLabel6");
        panelRound1.add(lblValorServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 93, 477, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Total de deuda:");
        panelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 131, -1, -1));

        lblValorTotalDeuda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblValorTotalDeuda.setText("jLabel8");
        panelRound1.add(lblValorTotalDeuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 131, 433, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Total pagado:");
        panelRound1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 169, -1, -1));

        lblValorTotalPagado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblValorTotalPagado.setText("jLabel10");
        panelRound1.add(lblValorTotalPagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 169, 126, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Saldo pendiente:");
        panelRound1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 207, -1, -1));

        lblValorSaldoPendiente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblValorSaldoPendiente.setText("jLabel12");
        panelRound1.add(lblValorSaldoPendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 207, 116, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Nuevo pago:");
        panelRound1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 245, -1, -1));

        txtNuevoPago.setText("jTextField1");
        panelRound1.add(txtNuevoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 245, 183, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Método de pago:");
        panelRound1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 285, -1, -1));

        cmbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONAR", "Efectivo", "Tarjeta", "Yape", "Plin", "Transferencia bancaria" }));
        panelRound1.add(cmbMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 285, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("FECHA DE PAGO:");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 325, -1, -1));

        lblValorFechaPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValorFechaPago.setText("jLabel6");
        panelRound1.add(lblValorFechaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 328, 112, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("ESTADO :");
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 363, -1, -1));

        lblValorEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblValorEstado.setText("jLabel8");
        panelRound1.add(lblValorEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 363, 110, -1));

        btnRegistrarPago.setBackground(new java.awt.Color(153, 255, 153));
        btnRegistrarPago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarPago.setText("GUARDAR");
        btnRegistrarPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRound1.add(btnRegistrarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 483, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRound1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 483, -1, -1));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 680, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iberoamericana1107-1000.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmRegistrarPago().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrarPago;
    private javax.swing.JComboBox<String> cmbMetodoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblValorEstado;
    private javax.swing.JLabel lblValorFechaPago;
    private javax.swing.JLabel lblValorSaldoPendiente;
    private javax.swing.JLabel lblValorServicio;
    private javax.swing.JLabel lblValorTotalDeuda;
    private javax.swing.JLabel lblValorTotalPagado;
    private vista.PanelRound panelRound1;
    private vista.PanelRound panelRound2;
    private javax.swing.JTextField txtNuevoPago;
    // End of variables declaration//GEN-END:variables
}
