/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import dao.UsuarioDAO;
import modelo.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controlador.Sesion;

/**
 *
 * @author chumuslavia
 */
public class FrmUsuarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmUsuarios.class.getName());
    private UsuarioDAO usuarioDAO;
private List<Usuario> listaUsuarios;

    /**
     * Creates new form FrmUsuarios
     */
    public FrmUsuarios() {
        initComponents();
    setLocationRelativeTo(null);

    this.usuarioDAO = new UsuarioDAO();

    Usuario usuarioActual = Sesion.getUsuarioActual();

    if (usuarioActual == null) {
        JOptionPane.showMessageDialog(
                this,
                "SESION NULL: no hay usuario guardado."
        );
    } else {
        JOptionPane.showMessageDialog(
                this,
                "Sesión activa:\n"
                + "Usuario: " + usuarioActual.getUsuario()
                + "\nRol: " + usuarioActual.getRol()
        );
    }

    cargarUsuarios();
    }
    
    private void abrirModificar(Usuario usuarioSeleccionado) {

    FrmModificarUsuario ventana =
            new FrmModificarUsuario(this, usuarioSeleccionado);

    this.setVisible(false);
    ventana.setVisible(true);
}
    
    
    
    private void cargarUsuarios() {

    listaUsuarios = usuarioDAO.listar();

    DefaultTableModel modelo =
            (DefaultTableModel) tblUsuarios.getModel();

    modelo.setRowCount(0);

    for (Usuario usuario : listaUsuarios) {

        modelo.addRow(new Object[]{
            usuario.getIdUsuario(),
            usuario.getUsuario(),
            usuario.getNombre(),
            usuario.getRol(),
            usuario.getEstado(),
            usuario.getFechaRegistro()
        });
    }
    
}
    public void actualizarUsuarios() {
    cargarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new vista.PanelRound();
        panelRound2 = new vista.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 627));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(153, 153, 153));
        panelRound2.setRoundTopLeft(30);
        panelRound2.setRoundTopRight(30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("GESTIÓN DE USUARIOS");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(385, 385, 385)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBuscar.setText("Buscar usuario:");
        panelRound1.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 55, -1, -1));
        panelRound1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 55, 653, -1));

        btnBuscar.setBackground(new java.awt.Color(153, 255, 153));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRound1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 55, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 51));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRound1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(883, 55, -1, -1));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario", "Nombre", "Rol", "Estado", "Fecha de registro"
            }
        ));
        jScrollPane1.setViewportView(tblUsuarios);
        if (tblUsuarios.getColumnModel().getColumnCount() > 0) {
            tblUsuarios.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblUsuarios.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblUsuarios.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblUsuarios.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblUsuarios.getColumnModel().getColumn(4).setPreferredWidth(10);
            tblUsuarios.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        panelRound1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 90, 948, 469));

        btnNuevo.setBackground(new java.awt.Color(153, 255, 153));
        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);
        panelRound1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 565, -1, -1));

        btnModificar.setBackground(new java.awt.Color(255, 255, 51));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        panelRound1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 565, -1, -1));

        btnCerrar.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrar.setText("CERRAR");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);
        panelRound1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 565, -1, -1));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iberoamericana1107-1000.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        FrmNuevoUsuario ventana = new FrmNuevoUsuario(this);
    ventana.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
          // =====================================================
    
    // =====================================================
    // 1. VERIFICAR SESIÓN
    // =====================================================

    Usuario usuarioActual = Sesion.getUsuarioActual();

    if (usuarioActual == null) {

        JOptionPane.showMessageDialog(
                this,
                "No hay una sesión activa.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }


    // =====================================================
    // 2. VERIFICAR USUARIO SELECCIONADO
    // =====================================================

    int fila = tblUsuarios.getSelectedRow();

    if (fila == -1) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccione un usuario de la tabla.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }


    // =====================================================
    // 3. OBTENER USUARIO SELECCIONADO
    // =====================================================

    int idUsuario = (int) tblUsuarios.getValueAt(fila, 0);

    Usuario usuarioSeleccionado =
            usuarioDAO.buscarPorId(idUsuario);

    if (usuarioSeleccionado == null) {

        JOptionPane.showMessageDialog(
                this,
                "No se pudo encontrar el usuario seleccionado.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }


    // =====================================================
    // 4. OBTENER ROLES
    // =====================================================

    String rolActual = usuarioActual.getRol();
    String rolSeleccionado = usuarioSeleccionado.getRol();


    // =====================================================
    // 5. OWNER
    // Puede modificar a cualquier usuario
    // =====================================================

    if ("Owner".equalsIgnoreCase(rolActual)) {

        abrirModificar(usuarioSeleccionado);
        return;
    }


    // =====================================================
    // 6. ADMINISTRADOR
    // Puede modificar:
    // - Recepción
    // - Médico
    // - Laboratorio
    //
    // NO puede modificar:
    // - Owner
    // - Administrador
    // =====================================================

    if ("Administrador".equalsIgnoreCase(rolActual)) {

        if ("Recepción".equalsIgnoreCase(rolSeleccionado)
                || "Médico".equalsIgnoreCase(rolSeleccionado)
                || "Laboratorio".equalsIgnoreCase(rolSeleccionado)) {

            abrirModificar(usuarioSeleccionado);
            return;
        }

        JOptionPane.showMessageDialog(
                this,
                "Un Administrador no puede modificar a "
                + rolSeleccionado + ".",
                "Acceso denegado",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }


    // =====================================================
    // 7. RECEPCIÓN
    // No puede modificar usuarios
    // =====================================================

    if ("Recepción".equalsIgnoreCase(rolActual)) {

        JOptionPane.showMessageDialog(
                this,
                "Recepción no tiene permisos para modificar usuarios.",
                "Acceso denegado",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }


    // =====================================================
    // 8. MÉDICO
    // No puede modificar usuarios
    // =====================================================

    if ("Médico".equalsIgnoreCase(rolActual)) {

        JOptionPane.showMessageDialog(
                this,
                "Médico no tiene permisos para modificar usuarios.",
                "Acceso denegado",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }


    // =====================================================
    // 9. LABORATORIO
    // No puede modificar usuarios
    // =====================================================

    if ("Laboratorio".equalsIgnoreCase(rolActual)) {

        JOptionPane.showMessageDialog(
                this,
                "Laboratorio no tiene permisos para modificar usuarios.",
                "Acceso denegado",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }


    // =====================================================
    // 10. ROL NO RECONOCIDO
    // =====================================================

    JOptionPane.showMessageDialog(
            this,
            "El rol del usuario no tiene permisos definidos.",
            "Acceso denegado",
            JOptionPane.WARNING_MESSAGE
    );
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        FrmMenuPrincipal ventanaMenuPrincipal = new FrmMenuPrincipal();
        ventanaMenuPrincipal.setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmUsuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private vista.PanelRound panelRound1;
    private vista.PanelRound panelRound2;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
